-- =========================================
-- MIGRACIÓN: Tablas Independientes para Proyecto Pablo
-- =========================================
-- Este script crea tablas separadas para el proyecto de Pablo,
-- permitiendo que coexistan dos proyectos independientes en la misma base de datos.

-- =========================================
-- PASO 1: CREAR TABLAS
-- =========================================

-- 1. Tabla: profiles_pablo
CREATE TABLE profiles_pablo (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  role TEXT,
  avatar TEXT,
  tone TEXT,
  niche_keywords TEXT[],
  target_creators TEXT[],
  custom_instructions TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla: creators_pablo
CREATE TABLE creators_pablo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  linkedin_url TEXT NOT NULL,
  headline TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla: posts_pablo
CREATE TABLE posts_pablo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  original_post_id TEXT,
  original_url TEXT,
  original_content TEXT,
  original_author TEXT,
  generated_content TEXT,
  type TEXT CHECK (type IN ('parasite', 'research', 'manual')),
  meta JSONB,
  status TEXT DEFAULT 'drafted',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================
-- PASO 2: HABILITAR ROW LEVEL SECURITY
-- =========================================

ALTER TABLE profiles_pablo ENABLE ROW LEVEL SECURITY;
ALTER TABLE creators_pablo ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts_pablo ENABLE ROW LEVEL SECURITY;

-- =========================================
-- PASO 3: POLÍTICAS RLS - PROFILES_PABLO
-- =========================================

CREATE POLICY "Users can view own profile_pablo" ON profiles_pablo
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile_pablo" ON profiles_pablo
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile_pablo" ON profiles_pablo
  FOR INSERT WITH CHECK (auth.uid() = id);

-- =========================================
-- PASO 4: POLÍTICAS RLS - CREATORS_PABLO
-- =========================================

CREATE POLICY "Users can view own creators_pablo" ON creators_pablo
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own creators_pablo" ON creators_pablo
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own creators_pablo" ON creators_pablo
  FOR DELETE USING (auth.uid() = user_id);

-- =========================================
-- PASO 5: POLÍTICAS RLS - POSTS_PABLO
-- =========================================

CREATE POLICY "Users can view own posts_pablo" ON posts_pablo
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own posts_pablo" ON posts_pablo
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own posts_pablo" ON posts_pablo
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own posts_pablo" ON posts_pablo
  FOR DELETE USING (auth.uid() = user_id);

-- =========================================
-- PASO 6: ÍNDICES PARA PERFORMANCE
-- =========================================

CREATE INDEX idx_creators_pablo_user_id ON creators_pablo(user_id);
CREATE INDEX idx_posts_pablo_user_id ON posts_pablo(user_id);
CREATE INDEX idx_posts_pablo_status ON posts_pablo(status);
CREATE INDEX idx_posts_pablo_type ON posts_pablo(type);

-- =========================================
-- PASO 7: FUNCIÓN Y TRIGGER (OPCIONAL)
-- =========================================
-- Descomenta si quieres auto-crear perfil al registrar nuevos usuarios

-- CREATE OR REPLACE FUNCTION public.handle_new_pablo_profile()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   INSERT INTO public.profiles_pablo (id, name, role, tone, custom_instructions)
--   VALUES (
--     new.id,
--     new.raw_user_meta_data->>'name',
--     'Financial Advisor',
--     'Professional',
--     'Asesor financiero corporativo especializado en empresas y ejecutivos.'
--   )
--   ON CONFLICT (id) DO NOTHING;
--   RETURN new;
-- END;
-- $$ LANGUAGE plpgsql SECURITY DEFINER;

-- CREATE TRIGGER on_auth_pablo_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE PROCEDURE public.handle_new_pablo_profile();

-- =========================================
-- VERIFICACIÓN
-- =========================================

-- Verificar que las tablas se crearon correctamente
SELECT table_name FROM information_schema.tables
WHERE table_name IN ('profiles_pablo', 'creators_pablo', 'posts_pablo')
ORDER BY table_name;

-- Verificar políticas RLS
SELECT tablename, policyname FROM pg_policies
WHERE tablename LIKE '%_pablo'
ORDER BY tablename, policyname;

-- =========================================
-- MIGRACIÓN DE DATOS (OPCIONAL)
-- =========================================
-- Si quieres copiar datos existentes de Pablo a las nuevas tablas,
-- reemplaza 'UUID_DE_PABLO' con el ID real del usuario y descomenta:

-- INSERT INTO profiles_pablo
-- SELECT * FROM profiles WHERE id = 'UUID_DE_PABLO';

-- INSERT INTO creators_pablo
-- SELECT * FROM creators WHERE user_id = 'UUID_DE_PABLO';

-- INSERT INTO posts_pablo
-- SELECT * FROM posts WHERE user_id = 'UUID_DE_PABLO';
